pipelines:
  - name: test_jenkins_escape_chars
    steps:
    - name: test_app
      type: Jenkins
      configuration:
        jenkinsJobName: master
        jenkinsBranchName: {{gitBranch}}
        integrations:
          - name: jenkins_aws
        outputResources:
          - name: jenkins_job_results