pipelines:
  - name: test_jenkins_escape_chars_master
    steps:
    - name: test_app
      type: Jenkins
      configuration:
        jenkinsJobName: test_escap_char
        jenkinsBranchName: {{gitBranch.replace(/\//g, '%2F')}}
        integrations:
          - name: jenkins
        outputResources:
          - name: jenkins_job_master
    - name: print_results
      type: Bash
      configuration:
        inputResources:
          - name: jenkins_job_master
      execution:
        onExecute:
          - printenv
