pipelines:
  - name: test_jenkins_escape_chars_master
    steps:
    - name: test_app
      type: Jenkins
      configuration:
        jenkinsJobName: mybuild/build2/escape_fwd_slash
        jenkinsBranchName: {{gitBranch}}
        integrations:
          - name: jenkins
        outputResources:
          - name: jenkins_job_master
    - name: print_results
      type: Bash
      configuration:
        inputResources:
          - name: jenkins_job_master
      execution:
        onExecute:
          - printenv
